const FRAME_RATE = 60; // 30 to 100 images per second
const MAX_SCORE = 50;
const PONG_WIDTH = 500;
const PONG_HEIGHT = 250;

const PADDLE_INITIAL_SPEED = 0.2;
const PADDLE_MIN_SPEED = 0.1;
const PADDLE_MAX_SPEED = 0.5;
const PADDLE_INITIAL_WIDTH = 6;
const PADDLE_INITIAL_HEIGHT = 60;

const BALL_INITIAL_SPEED = 0.2;
const BALL_INITIAL_WIDTH = 10;
const BALL_INITIAL_HEIGHT = 10;

const POWER_PROJECTILE_INITIAL_SPEED = 0.05;
const POWER_PROJECTILE_INITIAL_WIDTH = 10;
const POWER_PROJECTILE_INITIAL_HEIGHT = 10;

const POWER_LIFETIME = 10000; // milliseconds

const MAX_PROJECTILES = 10;
const PROJECTILES_DEFAULT_LIFETIME = 20000; // milliseconds
